#!/usr/bin/env python3
"""
Regenerate the Roll launcher icon.

The mark is a lens between two strips of sprocket holes: a camera and a roll of film in
one shape. White line art on black, matching the icon language of the sibling Light
Phone III tools.

Geometry is defined once, in the 108x108 adaptive-icon canvas, and emitted twice — as
Android vector paths and as raster fallbacks. Everything sits inside the 18..90 safe zone
so no launcher mask can clip it, and that is asserted rather than eyeballed.

    python3 scripts/generate_icon.py

Needs Pillow. Rewrites app/src/main/res/{drawable,mipmap-*}.
"""

from __future__ import annotations

import os

from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

CANVAS = 108
SAFE = (18, 90)

STROKE = 5.0
LENS = (54.0, 54.0)
LENS_R = 18.0

HOLE_W = 8.0
HOLE_H = 5.0
HOLE_R = 1.6
HOLE_XS = (24.0, 38.0, 52.0, 66.0, 80.0)
HOLE_TOP_Y = 22.5
HOLE_BOTTOM_Y = 80.5

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8


def check_safe_zone() -> None:
    lo, hi = SAFE
    edge = STROKE / 2
    extents = [
        (LENS[0] - LENS_R - edge, LENS[1] - LENS_R - edge),
        (LENS[0] + LENS_R + edge, LENS[1] + LENS_R + edge),
        (HOLE_XS[0], HOLE_TOP_Y),
        (HOLE_XS[-1] + HOLE_W, HOLE_BOTTOM_Y + HOLE_H),
    ]
    for x, y in extents:
        assert lo <= x <= hi and lo <= y <= hi, f"({x}, {y}) escapes the safe zone"


def ring_path(cx: float, cy: float, r: float) -> str:
    return (
        f"M {cx - r},{cy} A {r},{r} 0 1 0 {cx + r},{cy} "
        f"A {r},{r} 0 1 0 {cx - r},{cy} Z"
    )


def holes_path() -> str:
    parts = []
    for y in (HOLE_TOP_Y, HOLE_BOTTOM_Y):
        for x in HOLE_XS:
            r = HOLE_R
            parts.append(
                f"M {x + r},{y} "
                f"h {HOLE_W - 2 * r} a {r},{r} 0 0 1 {r},{r} "
                f"v {HOLE_H - 2 * r} a {r},{r} 0 0 1 {-r},{r} "
                f"h {-(HOLE_W - 2 * r)} a {r},{r} 0 0 1 {-r},{-r} "
                f"v {-(HOLE_H - 2 * r)} a {r},{r} 0 0 1 {r},{-r} Z"
            )
    return " ".join(parts)


def write_vectors() -> None:
    background = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Pure black. On the Light Phone III's panel these pixels are simply off. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h{CANVAS}v{CANVAS}h-{CANVAS}z" />
</vector>
"""

    foreground = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by scripts/generate_icon.py — edit the geometry there, not here.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
    <path
        android:pathData="{ring_path(*LENS, LENS_R)}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="{STROKE:g}"
        android:fillColor="#00000000"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />
    <path
        android:pathData="{holes_path()}"
        android:fillColor="#FFFFFF" />
</vector>
"""

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    os.makedirs(os.path.join(RES, "mipmap-anydpi-v26"), exist_ok=True)
    with open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w") as f:
        f.write(background)
    with open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground)
    for name in ("ic_launcher", "ic_launcher_round"):
        with open(os.path.join(RES, "mipmap-anydpi-v26", f"{name}.xml"), "w") as f:
            f.write(adaptive)


def render(px: int, circular: bool) -> Image.Image:
    s = SUPERSAMPLE
    img = Image.new("RGBA", (CANVAS * s, CANVAS * s), (0, 0, 0, 255))
    d = ImageDraw.Draw(img)
    w = STROKE * s

    cx, cy = LENS
    d.ellipse(
        [(cx - LENS_R) * s - w / 2, (cy - LENS_R) * s - w / 2,
         (cx + LENS_R) * s + w / 2, (cy + LENS_R) * s + w / 2],
        fill=(255, 255, 255, 255),
    )
    d.ellipse(
        [(cx - LENS_R) * s + w / 2, (cy - LENS_R) * s + w / 2,
         (cx + LENS_R) * s - w / 2, (cy + LENS_R) * s - w / 2],
        fill=(0, 0, 0, 255),
    )

    for y in (HOLE_TOP_Y, HOLE_BOTTOM_Y):
        for x in HOLE_XS:
            d.rounded_rectangle(
                [x * s, y * s, (x + HOLE_W) * s, (y + HOLE_H) * s],
                radius=HOLE_R * s,
                fill=(255, 255, 255, 255),
            )

    # Crop to the 72x72 the launcher actually shows, so the legacy raster matches what
    # the adaptive icon looks like under a mask.
    lo, hi = SAFE
    out = img.crop((lo * s, lo * s, hi * s, hi * s)).resize((px, px), Image.LANCZOS)

    if circular:
        mask = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(mask).ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
        mask = mask.resize((px, px), Image.LANCZOS)
        base = Image.new("RGBA", (px, px), (0, 0, 0, 0))
        base.paste(out, (0, 0), mask)
        out = base
    return out


def write_rasters() -> None:
    for dpi, px in DENSITIES.items():
        folder = os.path.join(RES, f"mipmap-{dpi}")
        os.makedirs(folder, exist_ok=True)
        render(px, False).save(os.path.join(folder, "ic_launcher.png"))
        render(px, True).save(os.path.join(folder, "ic_launcher_round.png"))


if __name__ == "__main__":
    check_safe_zone()
    write_vectors()
    write_rasters()
    print("icon regenerated in", os.path.normpath(RES))
